"""
ReportAgent — IC papers / board packs.
Output: StructuredReport (Markdown/PDF)
"""

from typing import Any
from apps.agents.base import BaseAgent


class ReportAgent(BaseAgent):
    name = "ReportAgent"
    description = "Generates IC papers and board packs from model data"
    tools = ["report_templates", "calc_engine"]
    output_types = ["StructuredReport"]

    async def execute(self, context: dict[str, Any]) -> dict[str, Any]:
        model_data = context.get("model_data", {})
        report_type = context.get("report_type", "ic_paper")
        audience = context.get("audience", "investment_committee")

        cover = model_data.get("cover", {})
        returns = model_data.get("returns", {})
        sensitivity = model_data.get("sensitivity", {})
        checks = model_data.get("checks", [])

        content = self._generate_report(cover, returns, sensitivity, checks, report_type)

        return self._build_result(
            data={"content": content, "format": "markdown", "report_type": report_type},
            confidence=0.9,
        )

    def _generate_report(self, cover, returns, sensitivity, checks, report_type):
        metrics = returns.get("metrics", [])
        metrics_rows = "\n".join(
            f"| {m.get('metric','')} | {m.get('base_case','')} | {m.get('stress_case','')} | {m.get('upside_case','')} | {m.get('status','')} |"
            for m in metrics
        )

        return f"""# {report_type.replace('_',' ').title()} — {cover.get('Project', 'Project')}

## Project Overview
- **Operator:** {cover.get('Operator', 'N/A')}
- **Location:** {cover.get('Location', 'N/A')}
- **Capex:** {cover.get('Total Capex', 'N/A')}
- **Construction:** {cover.get('Construction', 'N/A')}
- **Operations:** {cover.get('Operations', 'N/A')}

## Returns Summary
| Metric | Base | Stress | Upside | Status |
|--------|------|--------|--------|--------|
{metrics_rows}

## Model Quality
Health checks: {len(checks)} performed, {sum(1 for c in checks if c.get('status')=='PASS')} passed.

---
*Generated by InvestIQ ReportAgent*
"""
